### ISSUE TITLE
Non-linear solver not compatible with python versions >= 3.8

### ISSUE THREAD

**Issue by azournas** [Chaowu88/freeflux#1]
I am getting an error when running the file tutorial_synechocystis_inst_simulation.py, attached in this message. The jist of the problem is that openopt calls time.clock(), which is deprecated in python 3.3 and removed in python 3.8. As python 3.7 is not available in apple silicon, I can't think of an easy workaround.

For simulation purposes, since the fitter is not used, commenting out lines 23 and 24 from model.py, where the imports are happening, solves the problem, but it's not possible to run the estimation.

Is there a way to solve this issue with the existing code?

Thank you!

( freeflux % /Users/user/anaconda3/envs/freeflux/bin/python /Users/user/freeflux/tutorials/tutorial_synechocystis_inst_simulation.py
Traceback (most recent call last):
  File "/Users/user/freeflux/tutorials/tutorial_synechocystis_inst_simulation.py", line 7, in <module>
    from freeflux import Model
  File "/Users/user/anaconda3/envs/freeflux/lib/python3.9/site-packages/freeflux/__init__.py", line 7, in <module>
    from .core.model import Model
  File "/Users/user/anaconda3/envs/freeflux/lib/python3.9/site-packages/freeflux/core/model.py", line 23, in <module>
    from ..analysis.fit import Fitter
  File "/Users/user/anaconda3/envs/freeflux/lib/python3.9/site-packages/freeflux/analysis/fit.py", line 20, in <module>
    from ..solver.nlpsolver import MFAModel 
  File "/Users/user/anaconda3/envs/freeflux/lib/python3.9/site-packages/freeflux/solver/nlpsolver.py", line 13, in <module>
    from openopt import NLP
  File "/Users/user/anaconda3/envs/freeflux/lib/python3.9/site-packages/openopt/__init__.py", line 10, in <module>
    from oo import *
  File "/Users/user/anaconda3/envs/freeflux/lib/python3.9/site-packages/openopt/oo.py", line 4, in <module>
    from LP import LP as CLP
  File "/Users/user/anaconda3/envs/freeflux/lib/python3.9/site-packages/openopt/kernel/LP.py", line 1, in <module>
    from baseProblem import MatrixProblem
  File "/Users/user/anaconda3/envs/freeflux/lib/python3.9/site-packages/openopt/kernel/baseProblem.py", line 10, in <module>
    from ooIter import ooIter
  File "/Users/user/anaconda3/envs/freeflux/lib/python3.9/site-packages/openopt/kernel/ooIter.py", line 3, in <module>
    from time import time, clock
ImportError: cannot import name 'clock' from 'time' (unknown location)

**Comment by Chaowu88** [comment]
Hi azournas, please refer to https://freeflux.readthedocs.io/en/latest/installation.html#dependencies-and-compatibility. You can use the corrected files to replace those in the openopt installation path.
